"""Canon translator — export ContinuityOS canon + rules into the config files that
coding agents auto-load: **CLAUDE.md** (Claude Code), **AGENTS.md** (the cross-agent
standard), and **.cursor/rules/continuityos.mdc** (Cursor). One source of truth — your
canon — flows into every agent's rules. Regenerate any time with ``cos rules``; the
files carry a banner and are meant to be overwritten, not hand-edited.
"""
from __future__ import annotations
import os
from typing import Dict, List, Tuple

BANNER = ("Generated by ContinuityOS from canon — regenerate with `cos rules`. "
          "Edits here are overwritten.")

TARGET_PATHS = {
    "claude": "CLAUDE.md",
    "agents": "AGENTS.md",
    "cursor": os.path.join(".cursor", "rules", "continuityos.mdc"),
}


def _bullets(items: List[str]) -> str:
    items = [str(i).strip() for i in items if str(i).strip()]
    return "\n".join(f"- {t}" for t in items) if items else "- (none yet)"


def _gather(memory) -> Tuple[List[str], List[str], Dict[str, str]]:
    from .continuity import Continuity
    c = Continuity(memory=memory)
    canon = [r["text"] for r in sorted(c._dump("canon"), key=lambda r: r["id"])]
    rules = [r["text"] for r in sorted(memory.store.all_with_vecs(namespace="rules"),
                                       key=lambda r: r["id"])]
    frontiers = c.frontiers()
    return canon, rules, frontiers


def render_markdown(canon, rules, frontiers, title="Project rules") -> str:
    L = [f"# {title}", f"<!-- {BANNER} -->", "", "## Non-negotiable canon", _bullets(canon)]
    if rules:
        L += ["", "## Operating rules", _bullets(rules)]
    if frontiers:
        L += ["", "## Current focus", _bullets([f"{k}: {v}" for k, v in frontiers.items()])]
    return "\n".join(L) + "\n"


def render_cursor_mdc(canon, rules, frontiers) -> str:
    fm = ["---", "description: ContinuityOS canon and operating rules (auto-generated)",
          "alwaysApply: true", "---", ""]
    return "\n".join(fm) + render_markdown(canon, rules, frontiers, title="ContinuityOS rules")


def render(target: str, canon, rules, frontiers) -> str:
    if target == "cursor":
        return render_cursor_mdc(canon, rules, frontiers)
    return render_markdown(canon, rules, frontiers,
                           title="Project rules" if target == "claude" else "Agent rules")


def export_rules(memory, out_dir: str = ".", targets=("claude", "agents", "cursor"),
                 dry_run: bool = False) -> Dict:
    canon, rules, frontiers = _gather(memory)
    written: List[str] = []
    contents: Dict[str, str] = {}
    for t in targets:
        if t not in TARGET_PATHS:
            raise ValueError(f"unknown target {t!r}; choose from {sorted(TARGET_PATHS)}")
        text = render(t, canon, rules, frontiers)
        contents[t] = text
        if not dry_run:
            path = os.path.join(out_dir, TARGET_PATHS[t])
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(text)
            written.append(path)
    return {"canon": len(canon), "rules": len(rules), "frontiers": len(frontiers),
            "targets": list(targets), "written": written, "contents": contents}
