QUERY_SCHEMA = "continuityos.memory_federation_query/v2"
RESULT_SCHEMA = "continuityos.memory_federation_result/v1"
RESOLUTION_SCHEMA = "continuityos.memory_federation_resolution/v1"
RESPONSE_SCHEMA = "continuityos.memory_federation_response/v1"

MODES = frozenset({
    "DISCOVERY", "EVIDENCE", "CURRENT_STATE", "HISTORICAL_AS_OF",
    "OPERATIONAL_RECALL", "PHYSICAL_STATE",
})
SCOPES = frozenset({
    "RAW_CUSTODY", "FROZEN_EVIDENCE", "GOVERNED_KNOWLEDGE",
    "CURRENT_PROJECTION", "TWIN_OPERATIONAL",
})
SURFACE_SCOPE = {
    "RAW_CUSTODY": "RAW_CUSTODY",
    "R1_4R": "FROZEN_EVIDENCE",
    "R1_4R_ROUTER": "FROZEN_EVIDENCE",
    "POSTGRES_GOVERNED": "GOVERNED_KNOWLEDGE",
    "CONTROL_CENTER": "CURRENT_PROJECTION",
    "CONTINUITYOS_PROJECTION": "CURRENT_PROJECTION",
    "TWIN_NOMIC_768": "TWIN_OPERATIONAL",
}
MODE_AUTHORITY = {
    "DISCOVERY": frozenset({"RAW_EVIDENCE", "EVIDENCE_ONLY", "CURRENT_TRUTH", "OPERATIONAL_MEMORY"}),
    "EVIDENCE": frozenset({"RAW_EVIDENCE", "EVIDENCE_ONLY", "CURRENT_TRUTH"}),
    "CURRENT_STATE": frozenset({"CURRENT_TRUTH"}),
    "HISTORICAL_AS_OF": frozenset({"RAW_EVIDENCE", "EVIDENCE_ONLY", "CURRENT_TRUTH"}),
    "OPERATIONAL_RECALL": frozenset({"OPERATIONAL_MEMORY"}),
    "PHYSICAL_STATE": frozenset({"RAW_EVIDENCE", "EVIDENCE_ONLY", "CURRENT_TRUTH"}),
}
ADAPTER_ALLOWED_AUTHORITY = {
    "CHATGPT_LIBRARY_FILES": frozenset({"EVIDENCE_ONLY", "NONE"}),
    "GOOGLE_DRIVE_CONNECTOR": frozenset({"EVIDENCE_ONLY", "NONE"}),
    "ARCHIVEOS_RAW_CUSTODY": frozenset({"RAW_EVIDENCE", "EVIDENCE_ONLY", "NONE"}),
    "R1_4R_SQLITE_DIRECT": frozenset({"EVIDENCE_ONLY", "NONE"}),
    "ROBERT_MEMORY_ROUTER_V11": frozenset({"EVIDENCE_ONLY", "NONE"}),
    "POSTGRES_GOVERNED_FUTURE": frozenset({"EVIDENCE_ONLY", "NONE"}),
    "CONTROL_CENTER_CURRENT_PROJECTION": frozenset({"CURRENT_TRUTH", "NONE"}),
    "CONTINUITYOS_CURRENT_PROJECTION": frozenset({"CURRENT_TRUTH", "NONE"}),
    "TWIN_NOMIC_768": frozenset({"OPERATIONAL_MEMORY", "NONE"}),
    "REMOTE_MANUS_M01": frozenset({"NONE"}),
    "R4_MANUS_STAGING": frozenset({"EVIDENCE_ONLY", "NONE"}),
}
ADAPTER_ALLOWED_SURFACES = {
    "CHATGPT_LIBRARY_FILES": frozenset({"RAW_CUSTODY"}),
    "GOOGLE_DRIVE_CONNECTOR": frozenset({"RAW_CUSTODY"}),
    "ARCHIVEOS_RAW_CUSTODY": frozenset({"RAW_CUSTODY"}),
    "R1_4R_SQLITE_DIRECT": frozenset({"R1_4R"}),
    "ROBERT_MEMORY_ROUTER_V11": frozenset({"R1_4R_ROUTER"}),
    "POSTGRES_GOVERNED_FUTURE": frozenset({"POSTGRES_GOVERNED"}),
    "CONTROL_CENTER_CURRENT_PROJECTION": frozenset({"CONTROL_CENTER"}),
    "CONTINUITYOS_CURRENT_PROJECTION": frozenset({"CONTINUITYOS_PROJECTION"}),
    "TWIN_NOMIC_768": frozenset({"TWIN_NOMIC_768"}),
    "REMOTE_MANUS_M01": frozenset({"UNKNOWN"}),
    "R4_MANUS_STAGING": frozenset({"UNKNOWN"}),
}
ADAPTER_ALLOWED_BINDINGS = {
    "CHATGPT_LIBRARY_FILES": frozenset({"DIRECT_PROVIDER_OBJECT", "RAW_BYTES", "IMMUTABLE_RECEIPT", "UNBOUND"}),
    "GOOGLE_DRIVE_CONNECTOR": frozenset({"DIRECT_PROVIDER_OBJECT", "IMMUTABLE_RECEIPT", "UNBOUND"}),
    "ARCHIVEOS_RAW_CUSTODY": frozenset({"DIRECT_PROVIDER_OBJECT", "DIRECT_LOCAL_RUNTIME", "RAW_BYTES", "IMMUTABLE_RECEIPT", "UNBOUND"}),
    "R1_4R_SQLITE_DIRECT": frozenset({"NORMALIZED_EVIDENCE", "IMMUTABLE_RECEIPT", "UNBOUND"}),
    "ROBERT_MEMORY_ROUTER_V11": frozenset({"NORMALIZED_EVIDENCE", "UNBOUND"}),
    "POSTGRES_GOVERNED_FUTURE": frozenset({"NORMALIZED_EVIDENCE", "PROJECTION", "UNBOUND"}),
    "CONTROL_CENTER_CURRENT_PROJECTION": frozenset({"PROJECTION", "IMMUTABLE_RECEIPT", "UNBOUND"}),
    "CONTINUITYOS_CURRENT_PROJECTION": frozenset({"PROJECTION", "IMMUTABLE_RECEIPT", "UNBOUND"}),
    "TWIN_NOMIC_768": frozenset({"OPERATIONAL_MEMORY", "DIRECT_LOCAL_RUNTIME", "UNBOUND"}),
    "REMOTE_MANUS_M01": frozenset({"UNBOUND"}),
    "R4_MANUS_STAGING": frozenset({"IMMUTABLE_RECEIPT", "NORMALIZED_EVIDENCE", "UNBOUND"}),
}
ADAPTER_ALLOWED_FRESHNESS = {
    "CHATGPT_LIBRARY_FILES": frozenset({"FRESH_PROVIDER", "SEALED_HISTORICAL", "STALE", "UNPROVEN"}),
    "GOOGLE_DRIVE_CONNECTOR": frozenset({"FRESH_PROVIDER", "SEALED_HISTORICAL", "STALE", "UNPROVEN"}),
    "ARCHIVEOS_RAW_CUSTODY": frozenset({"FRESH_PROVIDER", "FRESH_LOCAL_RUNTIME", "SEALED_HISTORICAL", "STALE", "UNPROVEN"}),
    "R1_4R_SQLITE_DIRECT": frozenset({"SEALED_HISTORICAL", "STALE", "UNPROVEN"}),
    "ROBERT_MEMORY_ROUTER_V11": frozenset({"SEALED_HISTORICAL", "STALE", "UNPROVEN"}),
    "POSTGRES_GOVERNED_FUTURE": frozenset({"SEALED_HISTORICAL", "STALE", "UNPROVEN"}),
    "CONTROL_CENTER_CURRENT_PROJECTION": frozenset({"FRESH_LOCAL_RUNTIME", "SEALED_HISTORICAL", "STALE", "UNPROVEN"}),
    "CONTINUITYOS_CURRENT_PROJECTION": frozenset({"FRESH_LOCAL_RUNTIME", "SEALED_HISTORICAL", "STALE", "UNPROVEN"}),
    "TWIN_NOMIC_768": frozenset({"FRESH_LOCAL_RUNTIME", "SEALED_HISTORICAL", "STALE", "UNPROVEN"}),
    "REMOTE_MANUS_M01": frozenset({"STALE", "UNPROVEN"}),
    "R4_MANUS_STAGING": frozenset({"SEALED_HISTORICAL", "STALE", "UNPROVEN"}),
}
ADAPTER_PRIORITY = {
    "R1_4R_SQLITE_DIRECT": 10,
    "ROBERT_MEMORY_ROUTER_V11": 20,
    "CHATGPT_LIBRARY_FILES": 30,
    "GOOGLE_DRIVE_CONNECTOR": 30,
    "ARCHIVEOS_RAW_CUSTODY": 30,
    "POSTGRES_GOVERNED_FUTURE": 40,
    "CONTROL_CENTER_CURRENT_PROJECTION": 50,
    "CONTINUITYOS_CURRENT_PROJECTION": 50,
    "TWIN_NOMIC_768": 60,
    "REMOTE_MANUS_M01": 90,
    "R4_MANUS_STAGING": 90,
}
PHYSICAL_BINDINGS = frozenset({"DIRECT_PROVIDER_OBJECT", "DIRECT_LOCAL_RUNTIME", "RAW_BYTES"})
PHYSICAL_FRESHNESS = frozenset({"FRESH_PROVIDER", "FRESH_LOCAL_RUNTIME"})
MAX_CANDIDATES = 10_000
MAX_COVERAGE_ROWS = 1_000
