from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, FrozenSet, Iterator, Mapping, Optional, Protocol

from .models import ChainHead, EventRecord, VerifyResult

STORE_CONTRACT_VERSION = "sct.evidence-store/v1"


class EvidenceStore(Protocol):
    def append(self, kind: str, payload: Mapping[str, Any], *, ts: Optional[float] = None) -> EventRecord: ...
    def get(self, event_id: str) -> Optional[EventRecord]: ...
    def query(self, *, kind: Optional[str] = None, kinds: Optional[FrozenSet[str]] = None,
              since_seq: int = 0, until_seq: Optional[int] = None,
              limit: Optional[int] = None) -> Iterator[EventRecord]: ...
    def head(self) -> ChainHead: ...
    def verify(self, *, from_seq: int = 1, to_seq: Optional[int] = None) -> VerifyResult: ...
    def put_blob(self, data: bytes) -> str: ...
    def get_blob(self, sha256: str) -> bytes: ...
    def transaction(self) -> AbstractContextManager[None]: ...
    def capabilities(self) -> FrozenSet[str]: ...
