from pathlib import Path

p = Path("tests/test_sct_r13_live_wiring.py")
text = p.read_text(encoding="utf-8")

old_import = "from sct.baseline_r13 import baseline_policy_hashes\n"
new_import = "from sct.baseline_r13 import admitted_pool_sha256, admitted_segments, baseline_policy_hashes, build_arm_b_profile_rag\nfrom sct.r13_live_provenance import build_arm_b_live_provenance_receipt, canonical_evidence_blob\n"
if text.count(old_import) != 1:
    raise SystemExit(f"legacy test import target mismatch: {text.count(old_import)}")
text = text.replace(old_import, new_import, 1)

old = '''    inputs = build_standard_inputs(\n        scenario="Synthetic live-path wiring check",\n        options=("Alpha", "Beta", "Gamma"),\n        provider=model["model_repo_or_provider_id"],\n        model=model["model_repo_or_provider_id"],\n        model_version=model["model_revision"],\n        static_profile="P" * 100,\n        permitted_history="",\n        sct_state="S" * 100,\n        token_budget=512,\n        temperature=0.0,\n        reasoning="fixed",\n        frozen_at=9000.0,\n    )\n    arena.open_case(\n'''
new = '''    rows = [\n        {"segment_id":"profile-legacy","source_id":"raw","text":"I compare evidence before choosing Alpha Beta or Gamma.","observed_at":100.0,"profile_eligible":True,"admitted":True,"assistant_authored":False,"sct_only_derived":False,"authorship":"HUMAN_USER"},\n        {"segment_id":"history-legacy","source_id":"raw","text":"Previous synthetic decisions use reversible evidence gates.","observed_at":110.0,"profile_eligible":False,"admitted":True,"assistant_authored":False,"sct_only_derived":False,"authorship":"HUMAN_USER"},\n    ]\n    pool = admitted_pool_sha256(admitted_segments(rows, source_cutoff=200.0))\n    builder = build_arm_b_profile_rag(\n        scenario="Synthetic live-path wiring check",\n        options=("Alpha", "Beta", "Gamma"),\n        evidence_rows=rows,\n        source_cutoff=200.0,\n        target_context_bytes=512,\n        expected_admitted_pool_sha256=pool,\n    )\n    inputs = build_standard_inputs(\n        scenario="Synthetic live-path wiring check",\n        options=("Alpha", "Beta", "Gamma"),\n        provider=model["model_repo_or_provider_id"],\n        model=model["model_repo_or_provider_id"],\n        model_version=model["model_revision"],\n        static_profile=builder["static_profile"],\n        permitted_history=builder["permitted_history"],\n        sct_state="S" * builder["payload_bytes"],\n        token_budget=512,\n        temperature=0.0,\n        reasoning="fixed",\n        frozen_at=9000.0,\n    )\n    blob_sha = store.put_blob(canonical_evidence_blob(rows))\n    baseline = list(store.query(kind="R13_BASELINE_SPEC_SEALED"))[-1].payload\n    provenance = build_arm_b_live_provenance_receipt(\n        case_id="CASE-R13-GUARD",\n        scenario="Synthetic live-path wiring check",\n        options=("Alpha", "Beta", "Gamma"),\n        evidence_rows=rows,\n        evidence_blob_sha256=blob_sha,\n        source_cutoff=200.0,\n        target_context_bytes=512,\n        expected_admitted_pool_sha256=pool,\n        builder_output=builder,\n        profile_rag_snapshot_sha256=inputs["profile_rag"].snapshot_sha256,\n        baseline_manifest_sha256=baseline["baseline_manifest_sha256"],\n    )\n    store.append("R13_ARM_B_LIVE_PROVENANCE_VERIFIED", provenance)\n    arena.open_case(\n'''
if text.count(old) != 1:
    raise SystemExit(f"legacy test body target mismatch: {text.count(old)}")
p.write_text(text.replace(old, new, 1), encoding="utf-8")
